### ISSUE TITLE
Nuxt 3 example

### ISSUE THREAD

**Issue by GioChocolateBro** [spatie/nuxt2-flare-demo#1]
Hiya,

I've used this example to try get flare going inside a nuxt 3 project.
We are running into many issues trying to have this adapted in a nuxt 3 plugin.

Would you have any idea how to go about this.

We made a flare.client.js plugin file with this:

```
import { flare } from '@flareapp/flare-client';
import { flareVue } from '@flareapp/flare-vue';

export default defineNuxtPlugin((nuxtApp) => {
  if (nuxtApp.$config.public.appEnv === 'production') {
    flare.light(nuxtApp.$config.public.flareKey);
  }
  nuxtApp.vueApp.use(flareVue);
});
```

**Comment by Sam-Apostel** [comment]
Hi @GioChocolateBro 

I made a demo repo for nuxt 3 here: https://github.com/spatie/flare-demo-nuxt3
Feel free to open issues when something is not working like it should.
